### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by morcuended** [fact-project/pyeventio#109] opened 2018-12-07 18:08 UTC
Hi,

I just tried to install the new version via pip and I got this error:

```
[...]
building 'eventio.header' extension
creating build/temp.linux-x86_64-3.7
creating build/temp.linux-x86_64-3.7/eventio
gcc -pthread -B /home/dmorcuende/.local/miniconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/dmorcuende/.local/miniconda3/include/python3.7m -I/home/dmorcuende/.local/miniconda3/lib/python3.7/site-packages/numpy/core/include -c eventio/header.c -o build/temp.linux-x86_64-3.7/eventio/header.o
gcc: error: eventio/header.c: No such file or directory
error: command 'gcc' failed with exit status 1
```

Any idea of what is going on?

**Comment by dneise** [comment] 2018-12-08 09:44
Thank you for your interest and your feedback. I am looking into this, in the meantime, could you tell us how exactly you installed pyeventio with pip?

Did you install from pypi like this?

    pip install eventio

Or did you clone the repo from github and then installed it with pip, like:

    git clone <url> <local_path>
    pip install <local_path>

**Comment by dneise** [comment] 2018-12-08 09:50
Ah, also if you could mention the system (linux, mac, win?) the python version and if or if not you are using anaconda python. That would be great.

**Comment by dneise** [comment] 2018-12-08 10:09
I am currently traveling, so I cannot really test this, but I can give you some background info, what might be happening here. 

This project uses C-extensions to speed up some performance critical sections. But instead of writing C, we wrote this in Cython  a superset of Python. 

So the complete build process involves these steps:

 - compile Cython to C files (needs cython compiler)
 - compile C to binaries (only simple C compiler needed)

Since not everyone has a cython compiler, we decided to not require the end users to perform the first step (to make installation easier). From this follows, that we should ship the C files to the end user. 

The C files however are so called build artifacts, as the are the result of a compilation from the fundamental cython files (pyx extension). So we do not want to keep such build artifacts in the code repository.

Therefore we package the C files only into the archive on pypi where users are expected to download them from and install the package.

So either the packaging of the C files into the package on pypi did not work, and therefore your copy does not contain the C file.

Or you cloned the repo from github. Then it is expected that the C files are missing. In this case pip will first check if you happen to have cython installed. If so, it will use cython to compile the pyx files into C files. If you do not have cython installed it will simply fail, since the C files are not in the cloned repo from github.

I think, we might want to emit a more clear error message in case, cython is not installed and the C files are missing.

**Comment by MaxNoe** [comment] 2018-12-08 10:31
Ok, the error seems to be that if Cython is installed, it only treats the pyx files as sources, so the c files are left out from the sdist.

I'll add the the c-files to the `package_data` so they will be included.

**Comment by MaxNoe** [comment] 2018-12-08 10:59
I just made a new PyPI release (version `0.9.2`) and checked that the c files are included in the tar ball.

So it should install now without having cython installed.

Can you try? Just `pip install eventio`

**Closed** 2018-12-08 10:59 UTC

**Comment by MaxNoe** [comment] 2018-12-08 11:02
Ok, forgot to also include the c files in `eventio.simtel`, now done and version `0.9.3` is on PyPI soon.

**Comment by MaxNoe** [comment] 2018-12-08 11:09
0.9.3 is on PyPI and I tested installing it in a virtualenv that does not have anything but pip and setuptools. Works fine, so this should be fixed.

**Comment by morcuended** [comment] 2018-12-08 11:18
I installed it with pip after cloning the repository from the repository path. I'm using python 3.6 with miniconda in Linux. I think that cython was not installed in the conda enviroment I was using.

I tried `pip install eventio` directly from pypi and it successfully installed.

Thanks for your quick response and the sim_telarray implementation. I will play with it a bit.

**Comment by MaxNoe** [comment] 2018-12-08 12:06
I added a better error message for people not having cython who clone the repo.

If you cloned the repo and thus do not have the c files and you don't have cython, you now will get:
``` 
 File "setup.py", line 46, in <module>
    raise ImportError('You need `Cython` to build this project locally')
ImportError: You need `Cython` to build this project locally

```

**Comment by kishoreinvits** [comment] 2019-05-15 12:30
I am not abl eto install eventio using `pip install eventio`

Can you help me if this issue I am facing is related to above discussed.

Please see logs below. And let me know if you need more info.

```
PS C:\vvtweb> pip install eventio                                                                                                                                                                                        
Collecting eventio
  Using cached https://files.pythonhosted.org/packages/a0/5d/487eae8d8e2f76dd2920727b8372e4d76493959f1397623a2f4c4d98db78/eventio-0.20.3.tar.gz
    ERROR: using cython False
    running egg_info                                                                                                                                                                                                     
    creating pip-egg-info\eventio.egg-info                                                                                                                                                                               
    writing pip-egg-info\eventio.egg-info\PKG-INFO
    writing dependency_links to pip-egg-info\eventio.egg-info\dependency_links.txt
    writing requirements to pip-egg-info\eventio.egg-info\requires.txt
    writing top-level names to pip-egg-info\eventio.egg-info\top_level.txt
    writing manifest file 'pip-egg-info\eventio.egg-info\SOURCES.txt'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 255 in C:\Users\ContainerAdministrator\AppData\Local\Temp\pip-install-k1hd54qb\eventio\                                                                 
PS C:\vvtweb> pip3 install eventio==0.9.3                                                                                                                                                                                
Collecting eventio==0.9.3                                                                                                                                                                                                
  Downloading https://files.pythonhosted.org/packages/82/32/fd3b9545b8ee408c14de97001fab4160c239040804e9178bca92855d1b13/eventio-0.9.3.tar.gz (58.3MB)
     |????????????????????????????????| 58.3MB 35kB/s
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: using cython False
    running egg_info                                                                                                                                                                                                     
    creating pip-egg-info\eventio.egg-info                                                                                                                                                                               
    writing pip-egg-info\eventio.egg-info\PKG-INFO
    writing dependency_links to pip-egg-info\eventio.egg-info\dependency_links.txt
    writing entry points to pip-egg-info\eventio.egg-info\entry_points.txt
    writing requirements to pip-egg-info\eventio.egg-info\requires.txt
    writing top-level names to pip-egg-info\eventio.egg-info\top_level.txt
    writing manifest file 'pip-egg-info\eventio.egg-info\SOURCES.txt'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 255 in C:\Users\ContainerAdministrator\AppData\Local\Temp\pip-install-d1pvwp18\eventio\                                                                 
PS C:\vvtweb> pip install cython                                                                                                                                                                                         
Collecting cython
  Downloading https://files.pythonhosted.org/packages/7c/12/ea6522c28b8fbbfe729dd6b62285077fae460262ffc64941262ad0f013fe/Cython-0.29.7-cp36-cp36m-win_amd64.whl (1.7MB)
     |????????????????????????????????| 1.7MB 6.4MB/s
Installing collected packages: cython
Successfully installed cython-0.29.7
PS C:\vvtweb> pip3 install eventio
Collecting eventio
  Using cached https://files.pythonhosted.org/packages/a0/5d/487eae8d8e2f76dd2920727b8372e4d76493959f1397623a2f4c4d98db78/eventio-0.20.3.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: using cython True
    running egg_info
    creating pip-egg-info\eventio.egg-info
    writing pip-egg-info\eventio.egg-info\PKG-INFO
    writing dependency_links to pip-egg-info\eventio.egg-info\dependency_links.txt
    writing entry points to pip-egg-info\eventio.egg-info\entry_points.txt
    writing requirements to pip-egg-info\eventio.egg-info\requires.txt
    writing top-level names to pip-egg-info\eventio.egg-info\top_level.txt
    writing manifest file 'pip-egg-info\eventio.egg-info\SOURCES.txt'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 255 in C:\Users\ContainerAdministrator\AppData\Local\Temp\pip-install-fbfzxkvo\eventio\
```

**Comment by MaxNoe** [comment] 2019-05-15 12:45
It looks like you are on windows. Building C-extensions on windows is quite a hazzle and we don't build wheels for windows. 

If you are in Windows 10 and want to use pyeventio, I would recommend to look into the "Windows Subsystem for Linux".

If you want to try building it on windows, you will need a c compiler setup.

**Comment by dneise** [comment] 2019-05-15 13:01
Maybe one can find some guidelines about cython on windows here: 
https://cython.readthedocs.io/en/latest/src/quickstart/install.html

**Comment by kishoreinvits** [comment] 2019-05-15 13:27
Thanks for the quick reply. I tried this by installing cython via pip as well, if you see the logs I shared, there is a line ``. I will try a bit more to see what I might be missing here.

I am using a Python official windows docker image as below where I am able to reproduce this. Docker file below if you are interested in supporting windows systems.

```
# Official python 3.6 windows server 2016
FROM python:3.6.8-windowsservercore-ltsc2016

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

# Copy missing system32 binaries
COPY ./sys32 c:/Windows/system32

# download and install VC++ build tools 2015
ADD http://download.microsoft.com/download/5/f/7/5f7acaeb-8363-451f-9425-68a90f98b238/visualcppbuildtools_full.exe ./visualcppbuildtools_full.exe
RUN Start-Process -FilePath 'visualcppbuildtools_full.exe' -ArgumentList '/Passive','/NoRestart' -Wait
RUN Remove-Item .\visualcppbuildtools_full.exe
RUN Get-ChildItem -Path 'C:/Program Files (x86)'

# update pip setuptools
RUN pip install -U pip
RUN pip install --upgrade setuptools

# install required pip packages
RUN pip install eventio
```

**Comment by MaxNoe** [comment] 2019-05-15 13:32
Sorry that I ask, but I'm curious: why do you want to use eventio in a windows server docker container?

**Comment by MaxNoe** [comment] 2019-05-15 13:33
And again: You will need a workong C compiler. So you will need to install e.g. Microsoft Visual C Compiler.

https://visualstudio.microsoft.com/vs/features/cplusplus/?rr=https%3A%2F%2Fwww.google.com%2F

**Comment by kishoreinvits** [comment] 2019-05-15 13:40
Thanks for the link, I am already trying to install that. 

A flask webapp which we are shipping needs it. Unfortunately our deployment target is Windows server 2016 build 1607 which does not support Linux containers, hence windows container.

**Comment by MaxNoe** [comment] 2019-05-15 13:41
I would be really interested in learning more about that project, you have a link?

**Comment by kishoreinvits** [comment] 2019-05-15 13:41
Sorry, its not public :(

**Comment by MaxNoe** [comment] 2019-05-15 13:46
Is it for cta?

**Comment by MaxNoe** [comment] 2019-05-15 13:49
https://docs.python.org/3.3/extending/windows.html

**Comment by kishoreinvits** [comment] 2019-05-15 13:51
No, not for CTA.

**Comment by dneise** [comment] 2019-05-15 14:02
Now I am curious :-D ...

**Comment by dneise** [comment] 2019-05-15 14:17
> Best is when everyone code openly :)

Yes ... no need to hide anything when it comes to science, I think

**Comment by MaxNoe** [comment] 2019-05-15 14:21
MAGIC? HESS? VERITAS? MACE?

**Comment by thomasgas** [comment] 2019-05-15 15:07
> MAGIC? HESS? VERITAS? MACE?

Betting time 🤑: I'll go for MACE 🔭

**Comment by MaxNoe** [comment] 2019-05-16 08:02
I sucessfully installed this on windows after installing the Build Tools for Visual Studio 2019 from here:
https://visualstudio.microsoft.com/downloads/

**Comment by MaxNoe** [comment] 2019-05-16 10:33
I found a solution for running this in a Windows Docker container.
Contact me, if you want it.

**Comment by kishoreinvits** [comment] 2019-05-16 20:41
I feel it's better to post it here as it might help future readers who might be looking for this or similar kind of thing.

Please let me know how to contact you. My email id is in my GitHub profile. I will be more than glad to talk 😊

**Comment by MaxNoe** [comment] 2019-05-16 21:08
I will not do free support for a closed source app thats comercially developed for an experiment I do not work for.

However, if your company (in cologne, right?) is interested, I could maybe consult for a day or two.

Windows is not and will never be a target I'm willing to officially support here.

**Comment by kishoreinvits** [comment] 2019-05-17 03:48
Fair. How can you be contacted. I could not get any info to contact you on your profile. Hence my previous message.

Thanks to all of you for putting this awesome project and your support so far.

**Comment by MaxNoe** [comment] 2019-05-17 07:36
Sorry, my email is pretty public I thought: maximilian.noethe@tu-dortmund.de
